name: copypasta
description: "Syncronized clipboard and notes."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  url_launcher: any
  multicast_dns: any
  shared_preferences: any
  intl: any
  http: any
  uuid: any
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
